version: "3.9"
services:
  mysqldb:
    image: mysql
    ports: 
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - dbData:/var/lib/mysql
volumes:
  dbData:
